algoritmo "treininho's"
var
   A,B,C,D:INTEIRO
inicio
      A <- 2
      B <- 3
      C <- 5
      D <- (B\A)

      Escreva (RaizQ(25)=C)
      Escreva (NAO(2^B=7))
      Escreva ((5%2>=C)E(5*8=20+20))
      Escreva (A%B)
      Escreva (A\B)
      Escreva (D < A)
      Escreva (ABS(B-C))
      Escreva ((Pi)<>B)b
      Escreva
      Escreva
      Escreva ((B+A=C) E (5=7))
      Escreva ((A=B) OU (3<C))
       Escreval(NAO(A=C))
fimalgoritmo
