algoritmo "1-Olá, Mundo!"
// Função : um programa que mostre na tela a mensagem "Olá, Mundo!"
// Autor : Allana Bilar
// Data : 11/01/2023
// Seção de Declarações 

var
   mundo,ola:caractere
inicio
      Escreval ("Olá, Mundo!")
      
      Escreval ("ou")
      
      mundo<-"Olá, Mundo!"
      Escreval (mundo)
      
      Escreval ("ou")
      
      ola<-"Olá, "
      Escreva (ola,"Mundo!")
fimalgoritmo
