algoritmo "11-Delta de Equações do Segundo Grau"
// Função : Delta de Equações do Segundo Grau
// Autor : Allana Bilar
// Data : 11/01/2023
// Seção de Declarações 
var
   a,b,c,equa,delta:real
inicio
      Escreva("Digite o valor de a: ")
      Leia(a)
      Escreva("Digite o valor de b: ")
      Leia(b)
      Escreva("Digite o valor de c: ")
      Leia(c)
      delta<-b^2-4*a*c
      Escreva("O valor de Delta: ", delta)
fimalgoritmo
