algoritmo "3-Nome e o Salário de um Funcionário"
// Função : Nome e o Salário de um Funcionário
// Autor : Allana Bilar
// Data : 11/01/2023
// Seção de Declarações 
var
   nome:caractere
   salario:real
inicio
      Escreva ("Nome do Funcionário: ")
      Leia (nome)
      Escreva ("Salário: R$")
      Leia (salario)
      Escreva ("O funcionário ",nome," tem um salário de R$",salario," em Junho.")
fimalgoritmo
